name: solaris
dependencies:
  - python
  - pip
  - shapely
  - fiona
  - pandas
  - geopandas
  - opencv
  - numpy
  - gdal=2.4.1
  - tqdm=
  - rtree
  - networkx
  - rasterio
  - scipy=
  - scikit-image
  - tensorflow
  - pytorch
  - torchvision
  - pyyaml
  - pip:
    - affine==2.2.2
    - albumentations==0.2.3
    - rio-tiler==1.2.7
