version: 2
formats:
  - htmlzip

python:
  version: 3.6
  install:
    - requirements: .rtfd-requirements.txt
    - method: setuptools
      path: .


conda:
  environment: .readthedocs-environment.yml

build:
  image: latest
