name: solaris
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - affine=2.3.0
  - albumentations=0.4.3
  - fiona=1.8.13
  - gdal=3.0.2
  - geopandas=0.6.2
  - matplotlib=3.1.2
  - networkx=2.4
  - numpy=1.17.3
  - opencv=4.1.2
  - pandas=0.25.3
  - pyproj=2.4.2
  - pytorch=1.3.1
  - torchvision=0.4.2
  - pyyaml=5.2
  - rasterio=1.1.1
  - requests=2.22.0
  - rio-cogeo=1.1.6
  - rtree=0.9.3
  - scikit-image=0.16.2
  - scipy=1.3.2
  - shapely=1.6.4
<<<<<<< HEAD
  - tqdm=4.40.0
  - urllib3=1.25.7
=======
  - fiona=1.8.6
  - pandas=0.24.2
  - geopandas=0.5.0
  - opencv=3.4.4
  - numpy=1.16.3
  - gdal=2.4.1
  - tqdm=4.31.1
  - matplotlib=3.1.0
  - rtree=0.9.1
  - urllib3=1.24.3
  - networkx=2.3
  - rasterio=1.0.24
  - scipy=1.2.1
  - scikit-image=0.15.0
>>>>>>> 75448e5... pinning rtree to 0.9.1
  - tensorflow-gpu=1.13.1
  - cuda92
