name: Release Python package

on:
  workflow_run:
    workflows: [tests]
    branches: [main]
    types: [completed]

jobs:
  release:
    needs: test
    runs-on: ubuntu-latest
    name: Release package to PyPi
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Build and release 📦 to PyPI
        with:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          tox -e release

